// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zghntaxqwiegmjqdvetg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnaG50YXhxd2llZ21qcWR2ZXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4Mzk3MjUsImV4cCI6MjA2MzQxNTcyNX0.VVT1gETgl-ncyLAoCwejxsl0ZrE5gBMpLXAF_EzEIVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);