
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zghntaxqwiegmjqdvetg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnaG50YXhxd2llZ21qcWR2ZXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4Mzk3MjUsImV4cCI6MjA2MzQxNTcyNX0.VVT1gETgl-ncyLAoCwejxsl0ZrE5gBMpLXAF_EzEIVo";

console.log('Supabase connection details:');
console.log('URL:', SUPABASE_URL);
console.log('Project ID from URL:', SUPABASE_URL.split('//')[1].split('.')[0]);
console.log('Key prefix:', SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Test the connection on initialization
supabase.from('Clients').select('count', { count: 'exact', head: true }).then(({ count, error }) => {
  if (error) {
    console.error('Supabase connection test failed:', error);
  } else {
    console.log('Supabase connection test successful. Total clients in table:', count);
  }
});
